# Required items.
game: Doom
api: 1
steamID: 379720
uid: com.thegreatcabbage.doom
author: TheGreatCabbage
packageName: doom
features:
  - keymaps

# Optional items.
keymapConfig: C:\Users\$!USERNAME!$\Saved Games\id Software\DOOM\base\DOOMConfig.cfg

gameDirectory: DOOM
verificationPaths:
  - DOOMx64.exe